//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.2012
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Hamma_Beads.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class MisHamas : global::System.Configuration.ApplicationSettingsBase {
        
        private static MisHamas defaultInstance = ((MisHamas)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MisHamas())));
        
        public static MisHamas Default {
            get {
                return defaultInstance;
            }
        }
    }
}
